apiVersion: v1
kind: Service
metadata:
  name: angular-k8s-demo
  labels:
    app: angular-k8s-demo
spec:
  type: NodePort
  selector:
    app: angular-k8s-demo
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
